hma_app:
    resource: "@HMAAppBundle/Resources/config/routing.yml"
    prefix:   /

login:
    pattern:   /login
    defaults:  { _controller: HMAUserBundle:Security:login }

login_check:
    pattern:   /login_check

logout:
    pattern:   /logout
