<?php

namespace HMA\AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Fiche_clientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Fiche_clientRepository extends EntityRepository
{
}
