<?php

namespace HMA\AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Fiche_vehiculeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Fiche_vehiculeRepository extends EntityRepository
{
    public function getClient($immat)
    {
        $qb = $this->createQueryBuilder('v')
            ->where('v.immat = :immat')
            ->setParameter('immat', $immat)
            ->leftJoin('v.ficheclient', 'client')
            ->addSelect('client')
            ->getQuery()
            ->getResult()
        ;
        
        return $qb;
    }
}
